# Generated by Django 3.2.15 on 2022-08-28 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='appstore_config_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('Link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playstore_config_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('Link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('addres', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, max_length=200, null=True)),
                ('App_icon', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('app_email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('app_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('Maintaince_mode', models.BooleanField(default=True)),
                ('App_account', models.CharField(blank=True, max_length=200, null=True)),
                ('app_version', models.CharField(blank=True, max_length=200, null=True)),
                ('Playstore_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playstore', to='polls.playstore_config_class')),
                ('appstore_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appstore', to='polls.appstore_config_class')),
            ],
        ),
    ]
