# Generated by Django 3.2.15 on 2022-08-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='About_us',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='Termes_conditions',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='privacy_policy',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
