# Generated by Django 3.2.15 on 2022-08-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20220829_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
