# Generated by Django 3.2.15 on 2022-08-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Isverified',
            field=models.BooleanField(default=False),
        ),
    ]
