# Generated by Django 3.2.15 on 2022-08-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_profile_isverified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Email',
        ),
    ]
