# Generated by Django 3.2.15 on 2022-08-31 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0007_remove_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('color', models.CharField(blank=True, default='#0000FF', max_length=50, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
