# Generated by Django 3.2.15 on 2022-08-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_custom_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_button',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
