# Generated by Django 3.2.15 on 2022-09-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_vcard_vcf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcard',
            name='vcf_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
