# Generated by Django 3.2.15 on 2022-09-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_vcard_vcf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='platforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('domain', models.URLField(max_length=128, unique=True)),
                ('color', models.CharField(blank=True, default='#0000FF', max_length=50, null=True)),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
            ],
        ),
    ]
