# Generated by Django 3.2.15 on 2022-09-05 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_platforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('isDirectOn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('form_id', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('domain', models.URLField(max_length=128, unique=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, default='#0000FF', max_length=50, null=True)),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_data', to='polls.sociallinks')),
            ],
        ),
    ]
