# Generated by Django 3.2.15 on 2022-09-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_data_sociallinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='data',
        ),
        migrations.AddField(
            model_name='data',
            name='isDirectOn',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='socialLinks',
        ),
    ]
