# Generated by Django 3.2.15 on 2022-09-10 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favoritekey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='polls.favorite'),
        ),
    ]
