# Generated by Django 3.2.15 on 2022-09-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_profile_favoritekey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favoritekey',
        ),
    ]
