# Generated by Django 3.2.15 on 2022-09-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_alter_data_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='index_num',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
