# Generated by Django 3.2.15 on 2022-09-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_data_index_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platforms',
            old_name='color',
            new_name='color1',
        ),
        migrations.AddField(
            model_name='platforms',
            name='color2',
            field=models.CharField(blank=True, default='#0000FF', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='platforms',
            name='section',
            field=models.CharField(choices=[('1', '2')], default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
