# Generated by Django 3.2.15 on 2022-09-14 15:38

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20220914_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforms',
            name='info',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
      
        migrations.AlterField(
            model_name='platforms',
            name='section',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50),
        ),
    ]
