# Generated by Django 3.2.15 on 2022-09-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20220914_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='image',
            field=models.FileField(blank=True, default=' ', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platforms',
            name='image',
            field=models.FileField(blank=True, default=' ', upload_to=''),
            preserve_default=False,
        ),
    ]
