# Generated by Django 3.2.15 on 2022-09-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_auto_20220915_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforms',
            name='dialog_title',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platforms',
            name='error_message',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platforms',
            name='link_type',
            field=models.CharField(choices=[('1', 'username'), ('2', 'link')], default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platforms',
            name='domain',
            field=models.URLField(blank=True, max_length=128),
        ),
    ]
