# Generated by Django 3.2.15 on 2022-09-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_auto_20220915_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platforms',
            name='dialog_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='error_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
