# Generated by Django 3.2.15 on 2022-09-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_auto_20220915_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platforms',
            name='section',
            field=models.CharField(choices=[('Social media', 'Social media'), ('Contact info', 'Contact info'), ('For Business', 'For Business'), ('Payments', 'Payments'), ('Content', 'Content'), ('Music', 'Music'), ('More', 'More')], max_length=50),
        ),
    ]
