# Generated by Django 3.2.15 on 2022-09-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_auto_20220919_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
