# Generated by Django 3.2.15 on 2022-09-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0041_alter_profile_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='isDirectOn',
        ),
        migrations.AddField(
            model_name='profile',
            name='isDirectOn',
            field=models.BooleanField(default=False),
        ),
    ]
